#!/bin/bash
# AUTO-GENERATED by scripts/generate_config.py — do not edit by hand.
set -e

# Fix ownership of upload subdirectories for each SFTP user
mkdir -p /home/demo_openmrg/uploads/main
chown -R 1001:1001 /home/demo_openmrg/uploads/main
mkdir -p /home/demo_orange_cameroun/uploads/douala
chown -R 1002:1002 /home/demo_orange_cameroun/uploads/douala

# Execute the original atmoz/sftp entrypoint
exec /entrypoint "$@"
